FROM golang:1.22.5-alpine AS builder

WORKDIR /app
COPY ./backend/go.mod ./backend/go.sum ./
RUN go mod download

COPY ./backend/ ./

RUN go build -o server .

FROM alpine:3.18
WORKDIR /app

COPY --from=builder /app /app

EXPOSE 8080

CMD ["/app/server"]