services:
  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - ".minio.env"
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data
    command: server /data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ".backend.env"
    depends_on:
      - minio
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  minio-data:
